apiVersion: v1
kind: Node
metadata:
  name: my-node
  labels:
    environment: prod
spec:
  taints:
  - key: "dedicated"
    value: "true"
    effect: "NoSchedule"
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
